### ISSUE TITLE
Q: how are you using Bazelisk in the script when the Bazel binaries < 4.0 aren't on the server?

### ISSUE THREAD

**Issue by alexbird** [revolut-mobile/TensorFlowLiteC-binary#3]
Thanks so much for sharing this 🏆
Both because the binary is immediately useful to me, and because the script is a useful learning tool.

I have noticed that Bazelisk cannot currently build TFLite, nor can the correct Bazel binary (3.7.2) be downloaded manually. Has that changed in the short time since you shared this?

```
% bazelisk build --config=ios --cpu=ios_x86_64 -c opt tensorflow/lite/ios:TensorFlowLiteC_static_framework
2021/07/21 16:18:39 Downloading https://releases.bazel.build/3.7.2/release/bazel-3.7.2-darwin-arm64...
2021/07/21 16:18:40 could not download Bazel: HTTP GET https://releases.bazel.build/3.7.2/release/bazel-3.7.2-darwin-arm64 failed with error 404
```

**Comment by snyuryev** [comment]
Got the same error
```
2021/07/21 18:37:25 Downloading https://releases.bazel.build/3.7.2/release/bazel-3.7.2-darwin-arm64...
2021/07/21 18:37:26 could not download Bazel: HTTP GET https://releases.bazel.build/3.7.2/release/bazel-3.7.2-darwin-arm64 failed with error 404
```

Is it possible to fix it?

**Comment by alexbird** [comment]
I've built an unmodified Bazel 3.7.2 from source in the same way as the script builds its patched version. 
I recommend using the same Bazel 4.1.0 to build it. It won't build with the latest 5.0.0.

It would be lovely if Bazelisk just worked though. If I had to speculate I'd say Google removed old binaries from the server at some point, but 3.7.2 is cached on the author's machine.

**Comment by acecilia** [comment]
@alexbird @snyuryev Glad you found it useful! 🙌 

I just did the following:
* Removed my bazel cache folder: `rm -rf /private/var/tmp/_bazel_andres`
* Cloned clean the repo: `git clone https://github.com/revolut-mobile/TensorFlowLiteC-binary.git`
* Run `cd TensorFlowLiteC-binary && make build_2_5_0`
* Wait a lot of time 😄 

The script executed successfully. Maybe you experienced a temporary outage, or have some problematic VPN setup 🤔

**Comment by acecilia** [comment]
I am running from an intel macbook pro. If you are running from M1, that may be the issue.

I dont have time or an M1 mac to try this out. If you manage to find a solution, happy to take a PR 😄

**Comment by alexbird** [comment]
Ah, yes, I am indeed! Using it to update our own library.

I was conflating the issue with the lack of binaries < 4.1.0 for any platform on the Bazel download page (https://github.com/bazelbuild/bazel/releases)

**Comment by snyuryev** [comment]
@alexbird @acecilia I can confirm that build is working fine on intel Mac. 

But still has this issue on Mac with M1:
```
2021/07/21 18:37:25 Downloading https://releases.bazel.build/3.7.2/release/bazel-3.7.2-darwin-arm64...
2021/07/21 18:37:26 could not download Bazel: HTTP GET https://releases.bazel.build/3.7.2/release/bazel-3.7.2-darwin-arm64 failed with error 404
```

The interesting part - this issue appears after:
```
# Make arm64 simulator slice
${PATCHED_BAZEL_BIN} build --config=ios --cpu=ios_sim_arm64 -c opt tensorflow/lite/ios:${TENSORFLOW_TARGET}
mkdir -p "${SIM_ARM64_DIR}" && unzip bazel-bin/tensorflow/lite/ios/${TENSORFLOW_TARGET}.zip -d "${SIM_ARM64_DIR}"
```

I was able to get arm64 simulator framework.

**Comment by alexbird** [comment]
@snyuryev That makes sense, because Bazelisk isn't used until after that step.

I wonder if running Bazelisk via Rosetta would fix the issue for M1 Macs? But I'm not sure when I'll have time to try it here.

**Comment by acecilia** [comment]
> The interesting part - this issue appears after

Makes sense: at this point is the first time the script is using a prebuilt binary of bazel (through bazelisk), the other times we are building bazel from inside the script
